---
run:
  skip-dirs:
    - .gen

  skip-files:
    - .*_gen\.go$

linters-settings:
  golint:
    min-confidence: 0.1
  goimports:
    local-prefixes: github.com/lindsaygrace/sonarr-config-tool

linters:
  enable-all: true
  disable:
    - funlen
    - maligned
    - wsl
    - gomnd
    - testpackage
    - goerr113

    # Drives todos nuts
    - godox
